name: Validate dotnet

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - test-windows-2025-runner
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-2025]
        dotnet-version: ['6.0', '7.0', '8.0', '9.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear toolcache
        shell: pwsh
        run: __tests__/clear-toolcache.ps1 ${{ runner.os }}
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: ./
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Verify installed version
        shell: pwsh
        run: |
          __tests__/verify-dotnet.ps1 -Patterns "^${{ matrix.dotnet-version }}"
